Repository GSG-G11/WeatherApp, pull requests merged in 2022-02, with the labels that each got.

#3 uploading file
  css/css.style
  index.html
  js/dom.js
  js/logic.js
  js/test.js
Labels: Awaiting Review

#8 add imporatant section
  css/css.style
  css/style.css
  index.html
Labels: Done

#9 add daily section
  css/style.css
  index.html
Labels: Awaiting Review, Done

#10 addform
  css/style.css
  index.html
Labels: Awaiting Review

#14 11 fetch image
  .vscode/settings.json
  index.html
  js/dom.js
  js/logic.js
Labels: Done

#16 fetch daily weather
  index.html
  js/dom.js
Labels: Done

#18 handle error
  assets/error.png
  css/style.css
  index.html
  js/dom.js
  js/logic.js
Labels: Awaiting Review

#19 "handle error"
  assets/error.png
  css/style.css
  index.html
  js/dom.js
  js/logic.js
Labels: Done

#20 handel error 404
  index.html
Labels: Awaiting Review

#21 error 404
  assets/error.png
  css/style.css
  index.html
  js/dom.js
  js/logic.js
Labels: Done

#22 create readme file
  README.md
Labels: Awaiting Review

#25 edit readme
  README.md
Labels: Awaiting Review

#26 abstraction code
  assets/background.jpg
  assets/logo.png
  css/style.css
  index.html
  js/dom.js
  js/functions.js
  js/logic.js
  js/test.js
Labels: Done

#28 add icon
  css/style.css
  js/dom.js
Labels: Done

#29 edit file
  js/dom.js
  js/functions.js
Labels: Awaiting Review

#31 add landing page
  .vscode/settings.json
  README.md
  assets/favicon.ico
  css/index.css
  css/weather.css
  index.html
  weather/weather.html
Labels: Done

#32 edit readme
  README.md
Labels: Done

#34 edit api
  .gitignore
  README.md
  js/dom.js
  weather/weather.html
Labels: Done
